apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fo3qzjewr-go-gitops
  description: This is GitOps manifest for fo3qzjewr-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: fo3qzjewr-go
    janus-idp.io/tekton: fo3qzjewr-go
    backstage.io/kubernetes-id: fo3qzjewr-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fo3qzjewr-go
