apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fo3qzjewr-go
  janus-idp.io/tekton: fo3qzjewr-go
  backstage.io/kubernetes-id: fo3qzjewr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fo3qzjewr-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
