apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fo3qzjewr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fo3qzjewr-go 
  name: fo3qzjewr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fo3qzjewr-go 
